env:
  TERM: tmux-256color
  WINIT_X11_SCALE_FACTOR: "1"
font:
  normal:
    family: Hack Nerd Font 
  size: 14.0
  scale_with_dpi: true
dpi:
  x: 96.0
  y: 96.0
window:
  padding:
    x: 5
    y: 5
  dynamic_padding: true
  decorations: full
  opacity: 0.8
colors:
  # Default colors
  primary:
    background: '0x232323'
    foreground: '0xcdcecf'
    # Normal colors
