font:
  normal:
    family: Hack Nerd Font 
  size: 10.0
  scale_with_dpi: true
window:
  padding:
    x: 5
    y: 5
  dynamic_padding: true
  decorations: full
  opacity: 0.8
colors:
  # Default colors
  primary:
    background: '0x232323'
    foreground: '0xcdcecf'
    # Normal colors
