'ui.selection' = {bg = 'gray'}
'ui.cursor' = { bg = 'white', fg = 'black' }
'ui.cursor.match' = {fg = 'cyan', modifiers = ['bold','underlined']}
'ui.statusline' = { bg = 'gray', modifiers = ['bold']}
'ui.linenr' = { fg = 'gray' }
'ui.linenr.selected' = { fg = 'white' }
'ui.menu' = { bg = 'gray' }

'type' = { fg = 'blue' }
'constant' = {fg = 'green' }
'string' = { fg = 'cyan' }
'comment' = { fg = 'gray' }
'function' = { fg = 'green' }
'variable' = { fg = 'magenta' }
'keyword' = { fg = 'light-blue' }
'tag' = { fg = 'light-green' }
'error' = { fg = 'red' }

'diagnostic' = {modifiers = ['underlined']}
'diagnostic.error' = { fg = 'red', modifiers = ['underlined']}

'markup.list' = { fg = 'yellow' }
'markup.bold' = { modifiers = ['bold'] }
'markup.italic' = { modifiers = ['italic'] }
'markup.link.url' = { fg = 'yellow' }
'markup.heading' = { fg = 'cyan', modifiers = ['bold']}

'ui.menu.selected' = { fg = 'green', bg = 'black' }
'ui.menu' = { fg = 'white', bg = 'black' }
'ui.statusline' = { fg = 'white' , bg = 'black' , modifiers = ['bold'] }
'ui.selection' = { bg = 'black', fg = 'gray'}
