'ui.selection' = {bg = 'black'}
'ui.cursor' = { bg = 'white', fg = 'black' }
'ui.cursor.match' = {fg = 'cyan', modifiers = ['bold','underlined']}
'ui.statusline' = { bg = 'gray', modifiers = ['bold']}
'ui.linenr' = { fg = 'gray' }
'ui.menu' = { bg = 'gray' }

'type' = { fg = 'blue' }
'constant' = {fg = 'green' }
'string' = { fg = 'cyan' }
'comment' = { fg = 'gray' }
'variable' = { fg = 'magenta' }
'keyword' = { fg = 'light-blue' }
'tag' = { fg = 'light-green' }
'error' = { fg = 'red' }