#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom --experimental-backends &
nitrogen --restore &
killall polybar; polybar top &
dunst &

pipewire &
pipewire-pulse &
setxkbmap es &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           10
bspc config focused_border_color "#20d3df"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Screenkey manage=off
bspc rule -a discord desktop='^10'
bspc rule -a Alacritty desktop='^1'
bspc rule -a Chromium desktop='^2'
bspc rule -a Zathura state=tiled
bspc rule -a epicgameslauncher.exe desktop='^6'
bspc rule -a Steam desktop='^4'
