#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom --experimental-backends &
nitrogen --restore &
killall polybar; polybar top &
dunst &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           10
bspc config focused_border_color "#20d3df"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Screenkey manage=off
bspc rule -a Steam state=floating desktop='^4'
bspc rule -a discord desktop='^10'
bspc rule -a alacritty desktop='^1'
bspc rule -a Zathura state=tiled
